Click to move edits
hongquanli/octopi-research pull request #128
Opened 2024-11-09 01:07 UTC by sohamazing

ENABLE_DEFAULT_CLICK_TO_MOVE = True
- no click-to-move checkbox (default on) 
- click to move off during acquisition
- click to move on after acquisition

ENABLE_DEFAULT_CLICK_TO_MOVE = False
- shows click-to-move checkbox in navigationWidget
- checkbox disabled during acquisition
- click to move off during acquisition
- click to move and checkbox restored after acquisition to previous state

2024-11-10 23:32 UTC, hongquanli requested changes
@sohamazing we should use the native double click implementation. See https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsscene/mouseclickevent.html

2024-11-11 22:12 UTC, sohamazing commented
changed to native pyqt mouse click double()

2024-11-14 22:19 UTC, hongquanli requested changes

2024-11-14 22:19 UTC, hongquanli commented on software/control/_def.py
suggestion 1: `ENABLE_DEFAULT_CLICK_TO_MOVE` -> `ENABLE_CLICK_TO_MOVE_BY_DEFAULT`
suggestion 2: since double click is hard to happen by mistake, we can remove this flag and enable click to move by default.

2024-11-14 22:19 UTC, hongquanli commented on software/control/core.py
`click_to_move` does not belong to NavigationController. It should be with the widget.

2024-11-22 04:47 UTC, sohamazing commented on software/control/_def.py
for suggestion 2 that means we would have click to move always on since we have removed the click to move checkbox? correct

2024-11-22 20:27 UTC, hongquanli commented on software/control/_def.py
yes

2024-11-24 02:12 UTC, hongquanli commented on software/control/core.py
Since there are too many places using `click_to_move`, makes sense for this change to be in a separate PR.

2024-11-24 02:16 UTC, merged